micronaut:
  application:
    name: jsonblob
  metrics:
    enabled: true
    export:
      newrelic:
        enabled: false
  router:
    static-resources:
        json-blob:
          paths:
            - classpath:static-resources
  server:
    cors:
      enabled: true
      configurations:
        web:
          exposedHeaders:
            - X-jsonblob
            - Location
            - Date
            - Content-Type
            - Accept
            - Origin